### ISSUE TITLE
AMISSL_INLINE_H doesn't fully work with the 5.x SDK's

### ISSUE THREAD

**Issue by patrikaxelsson** [jens-maus/amissl#66]
Got a 5.x SDK VBCC issue which is similar to #56. The AMISSL_INLINE_H workaround which works with the 4.x SDK's does not fully work with the 5.x SDK's.
 
What is similar:
- Defining AMISSL_INLINE_H makes it possible to compile and link executables without a global AmiSSLBase.
- The exe gets much larger by just including <proto/amissl.h>, even if no AmiSSL functions are used.
- Compiling with -O3 reduces the size to expected.
```
$ cat HelloAmiSSLTest.c 
#include <proto/exec.h>
#include <proto/dos.h>
#include <proto/amissl.h>

#include <exec/exec.h>
#include <dos/dos.h>

LONG HelloAmiSSLTest(void) {
	struct ExecBase *SysBase = *(struct ExecBase **) 4;
	struct DosLibrary *DOSBase = NULL;

	DOSBase = (void *) OpenLibrary("dos.library", 37);
	if (NULL == DOSBase) {
		return RETURN_FAIL;
	}

	Printf("Hello!\n");
	
	CloseLibrary((void *) DOSBase);
	return RETURN_OK;
}
$ make HelloAmiSSLTest HelloAmiSSLTest_O3
vc +aos68k -nostdlib -c99 -O2 -lvc -D__NOLIBBASE__ -DAMISSL_INLINE_H -IAmiSSL/Developer/include -o HelloAmiSSLTest HelloAmiSSLTest.c
vc +aos68k -nostdlib -c99 -O3 -lvc -D__NOLIBBASE__ -DAMISSL_INLINE_H -IAmiSSL/Developer/include -o HelloAmiSSLTest_O3 HelloAmiSSLTest.c
$ ls -la HelloAmiSSLTest HelloAmiSSLTest_O3
-rwxr-xr-x  1 patrik  access_bpf  6828 13 Okt 21:31 HelloAmiSSLTest*
-rwxr-xr-x  1 patrik  access_bpf   132 13 Okt 21:32 HelloAmiSSLTest_O3*
```

What is new:
- Defining AMISSL_INLINE_H does not reduce the executable size to expected, unused code is still added to it.
- The unused code is placed before the first function in your file, so if your first function is your startup function, the Amiga will execute the unused code instead of the startup function. This is perhaps not an issue in itself, but just a result.
```
> list NOHEAD HelloAmiSSLTest HelloAmiSSLTest_O3 
HelloAmiSSLTest                6828 ---arwed Idag      20:48:22
HelloAmiSSLTest_O3              132 ---arwed Idag      20:48:22
> HelloAmiSSLTest 
> echo $RC 
4096
> HelloAmiSSLTest_O3 
Hello!
> echo $RC 
0
```

Including example code: [HelloAmiSSLTest.zip](https://github.com/jens-maus/amissl/files/9780245/HelloAmiSSLTest.zip)

**Comment by Futaura** [comment]
This is because there used to be a lot of inline functions defined in `amissl/inline.h`, but OpenSSL 3.0 did away with most of those, replacing them with macros instead, which is good! Only `DEFINE_SPECIAL_STACK_OF(OPENSSL_PSTRING, OPENSSL_STRING)` remains. We had to do it this way originally to delay their definition, because those inline functions referenced AmiSSLBase / IAmiSSL.

However, the new macros that that replaced the inline functions actually call new inline functions to perform type checking:

https://github.com/jens-maus/amissl/blob/f230aa4feeea6e27f05e0a00eb6aa1231370d995/include/openssl/safestack.h#L46

But, those inline functions do not reference AmiSSLBase like before, so there is no real need to mess with them - GCC (at `-O1`or above) and SAS/C (`OptimizerGlobal`) have no trouble optimising them out at a basic level, as does `VBCC -O3`. In VBCC, `-O2` expands `-O=1023` - if you really do not want to use `-O3` then you could try `-O17407` (which is the same as `-O2` but with bit 14 set) to remove unused static functions. Likewise, `-O1` expands to `-O991`, so `-O=17375` is the equivalent. Or does this still use too much memory, as with `-O3`?

**Comment by Futaura** [comment]
> There still seems to be references to AmiSSLBase somewhere if I skip -DAMISSL_INLINE_H, is this expected?

Yes. `DEFINE_SPECIAL_STACK_OF` ultimately maps to `SKM_DEFINE_STACK_OF` in `amissl/inline.h`. Not sure why the OpenSSL team left that one in - maybe they'll convert it to the new approach at some point.

> I would definately wish that I did not have to use a specific compiler optimization level or feature to get the expected behaviour of the executable.
> 
> One could argue about the merits around why vbcc doesn't optimize away unused static functions at -O1 and above like gcc, but even if you used gcc, you would get different exe behaviour between -O0 and -O1 in this case.

The difference is that GCC and SAS/C optimise away unused static functions by default when optimisation is enabled at the lowest level, yet VBCC can only do it at `-O3`.

You could modify `openssl/safestack.h` if you wanted by redefining the following macro as a complete no-op:

`#define SKM_DEFINE_STACK_OF_INTERNAL(a,b,c)`

and delete the existing macro. I haven't tried this, so not sure if it will work - it obviously won't if your code uses any of these functions, directly or indirectly.

**Comment by patrikaxelsson** [comment]
> You could modify `openssl/safestack.h` if you wanted by redefining the following macro as a complete no-op:
> 
> `#define SKM_DEFINE_STACK_OF_INTERNAL(a,b,c)`
> 
> and delete the existing macro. I haven't tried this, so not sure if it will work - it obviously won't if your code uses any of these functions, directly or indirectly.

It works to some extent as the file size is more than halved compared to before at -O2, I guess there is some other static function somewhere else:
```diff
$ diff -u AmiSSL/Developer/include/openssl/safestack.h{.backup,}
--- AmiSSL/Developer/include/openssl/safestack.h.backup	2022-10-11 20:25:33.000000000 +0200
+++ AmiSSL/Developer/include/openssl/safestack.h	2022-10-15 00:43:17.000000000 +0200
@@ -42,36 +42,7 @@
 
 # define STACK_OF(type) struct stack_st_##type
 
-/* Helper macro for internal use */
-# define SKM_DEFINE_STACK_OF_INTERNAL(t1, t2, t3) \
-    STACK_OF(t1); \
-    typedef int (*sk_##t1##_compfunc)(const t3 * const *a, const t3 *const *b); \
-    typedef void (*sk_##t1##_freefunc)(t3 *a); \
-    typedef t3 * (*sk_##t1##_copyfunc)(const t3 *a); \
-    static ossl_unused ossl_inline t2 *ossl_check_##t1##_type(t2 *ptr) \
-    { \
-        return ptr; \
-    } \
-    static ossl_unused ossl_inline const OPENSSL_STACK *ossl_check_const_##t1##_sk_type(const STACK_OF(t1) *sk) \
-    { \
-        return (const OPENSSL_STACK *)sk; \
-    } \
-    static ossl_unused ossl_inline OPENSSL_STACK *ossl_check_##t1##_sk_type(STACK_OF(t1) *sk) \
-    { \
-        return (OPENSSL_STACK *)sk; \
-    } \
-    static ossl_unused ossl_inline OPENSSL_sk_compfunc ossl_check_##t1##_compfunc_type(sk_##t1##_compfunc cmp) \
-    { \
-        return (OPENSSL_sk_compfunc)cmp; \
-    } \
-    static ossl_unused ossl_inline OPENSSL_sk_copyfunc ossl_check_##t1##_copyfunc_type(sk_##t1##_copyfunc cpy) \
-    { \
-        return (OPENSSL_sk_copyfunc)cpy; \
-    } \
-    static ossl_unused ossl_inline OPENSSL_sk_freefunc ossl_check_##t1##_freefunc_type(sk_##t1##_freefunc fr) \
-    { \
-        return (OPENSSL_sk_freefunc)fr; \
-    }
+#define SKM_DEFINE_STACK_OF_INTERNAL(a,b,c)
 
 # if defined(OPENSSL_SYS_AMIGA) && !defined(AMISSL_COMPILE)
 # define SKM_DEFINE_STACK_OF(t1, t2, t3) \
```
```
$ make HelloAmiSSLTest
vc +aos68k -nostdlib -c99 -O2 -lvc -D__NOLIBBASE__ -DAMISSL_INLINE_H -IAmiSSL/Developer/include -o HelloAmiSSLTest HelloAmiSSLTest.c
$ ls -la HelloAmiSSLTest
-rwxr-xr-x  1 patrik  access_bpf  3276 15 Okt 00:45 HelloAmiSSLTest*
```

**Comment by Futaura** [comment]
Ok, so yes, more here:

https://github.com/jens-maus/amissl/blob/f230aa4feeea6e27f05e0a00eb6aa1231370d995/include/openssl/err.h#L253

And more importantly here (lots of functions generated using this macro):

https://github.com/jens-maus/amissl/blob/f230aa4feeea6e27f05e0a00eb6aa1231370d995/include/openssl/core_dispatch.h#L59

There's nothing I can really do to workaround this without breaking the OpenSSL includes.

**Comment by patrikaxelsson** [comment]
Unless all these functions easily can be removed using something like -DAMISSL_INLINE_H, I think the tip about enabling the feature to remove the unused static functions in vbcc is the most user-friendly solution.

It would be more obvious that they will add/change the code of your executable if the files with these functions ended in .c - would make you react if you needed to include openssl.c for certain functionality. Or perhaps they could be provided as a link library.

To give an idea about the difference between -O2 and -O3 in vbcc, I have a small AmiSSL-dependant project here which compiles to 6816B with -O=17407 (-O2) and 10164B with -O3.

**Comment by patrikaxelsson** [comment]
Sorry, did not mean to close it.

Final question is if it is possible to add exclusion of these functions to -DAMISSL_INLINE_H or similar?

**Comment by Futaura** [comment]
I'm pondering `-DAMISSL_NO_STATIC_FUNCTIONS`, which would replace the `-DAMISSL_INLINE_H` hack. The problem will be if your code needs any of these functions (perhaps indirectly), it won't compile - the only solution then is to `-O3` because you really do want VBCC to hopefully inline those functions as that will be most optimal.

Moving them to a link library is not a solution - all these functions are really trivial, so they are supposed to be inlined by the the compiler, which wouldn't be possible with a link library. Some of these functions actually do nothing when it comes to code generation and are there only to check types of arguments passed into macros, to trigger a compiler warning if an incorrect parameter is passed.

They also can't really be moved to a single file as many of those functions are declared via a macro. The macro can be changed to not declare them, but moving the macro calls to a separate file is hard to manage given many of the OpenSSL header files will be using these macros.

**Comment by patrikaxelsson** [comment]
If you are fiddling with such options, it would not be unreasonable to suspect those if it does not compile.

`-DAMISSL_NO_STATIC_FUNCTIONS` is a much more explanatory name than `-DAMISSL_INLINE_H` btw.

**Comment by Futaura** [comment]
If you grab the 5 updated header files referenced in https://github.com/jens-maus/amissl/commit/0467dc10ef88e20245b979581f50ea8238cf91d6, you should be able to compile with `-DAMISSL_NO_STATIC_FUNCTIONS` which should solve this issue.

**Comment by patrikaxelsson** [comment]
Works great and no need to use -DAMISSL_INLINE_H to avoid references to AmiSSLBase either:
```
$ make HelloAmiSSLTest HelloAmiSSLTest_O3
vc +aos68k -nostdlib -c99 -O2 -lvc -D__NOLIBBASE__ -DAMISSL_NO_STATIC_FUNCTIONS -IAmiSSL/Developer/include -o HelloAmiSSLTest HelloAmiSSLTest.c
vc +aos68k -nostdlib -c99 -O3 -lvc -D__NOLIBBASE__ -DAMISSL_NO_STATIC_FUNCTIONS -IAmiSSL/Developer/include -o HelloAmiSSLTest_O3 HelloAmiSSLTest.c
$ ls -la HelloAmiSSLTest HelloAmiSSLTest_O3
-rwxr-xr-x  1 patrik  access_bpf  132 23 Okt 02:53 HelloAmiSSLTest*
-rwxr-xr-x  1 patrik  access_bpf  132 23 Okt 02:53 HelloAmiSSLTest_O3*
```

**Comment by patrikaxelsson** [comment]
Fixed!
